package edu.ait.ds.corba;


/**
* edu_ait_ds_corba/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Thursday, 9 March, 2023 10:29:36 AM IST
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
