package edu.ait.ds.corba;

/**
* edu_ait_ds_corba/CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Thursday, 9 March, 2023 10:29:36 AM IST
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public edu.ait.ds.corba.Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (edu.ait.ds.corba.Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = edu.ait.ds.corba.CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    edu.ait.ds.corba.CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return edu.ait.ds.corba.CalculatorHelper.type ();
  }

}
