package edu.ait.ds.corba;


/**
* edu_ait_ds_corba/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Thursday, 9 March, 2023 10:29:36 AM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
  int subtract (int a, int b);
  int multiply (int a, int b);
  int divide (int a, int b);
  void shutdown ();
} // interface CalculatorOperations
